paths:
  /api/products/:
    post:
      summary: Crea un nuevo producto
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/updateUser'
      responses:
        "200":
          description: El producto fue creado satisfactoriamente
          content: 
            application/json:
              schema:
                $ref: '#components/schemas/Products'
        "500":
          description: Error interno del servidor
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos satisfactoriamente
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Products'
        "500":
          description: Error interno del servidor
  /api/products/{pid}:
    get:
      summary: Obtiene el producto según su Id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Id del producto
          schema:
            $type: String
      responses:
        "200":
          description: El producto fue obtenido satisfactoriamente
          content: 
            application/json:
              schema:
                $ref: '#components/schemas/Products'
        "500":
          description: Error interno del servidor
    put:
      summary: Modifica un producto según su Id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Id del producto
          schema:
            $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/updateUser'
      responses:
        "200":
          description: El producto fue modificado satisfactoriamente
          content: 
            application/json:
              schema:
                $ref: '#components/schemas/Products'
        "500":
          description: Error interno del servidor
    delete:
      summary: Elimina el producto según su Id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Id del producto
          schema:
            $type: String
      responses:
        "200":
          description: El producto fue eliminado satisfactoriamente
          content: 
            application/json:
              schema:
                type: object
                properties:
                  status: 
                    type: string
                    example: success
                  message:
                    type: string
                    example: Producto eliminado correctamente
        "500":
          description: Error interno del servidor
components:
  schemas:
    Products:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerado por MongoDB
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripción del producto
        price:
          type: Number
          description: Precio del producto
        thumbnails:
          type: Array
          description: Fotos del producto
        code:
          type: String
          description: Código del producto
        stock:
          type: Number
          description: Cantidad de productos en stock
        category:
          type: String
          description: Categoría del producto
        status:
          type: Boolean
          description: Disponibilidad del producto
        owner:
          type: String
          description: Creador del producto
      example:
        _id: 654e8d9cdd7bc5ac119b66c0
        title: Valle de Punilla + Traslasierra
        description: 7 días, 6 noches
        price: 100
        thumbnails: [Sin imagen]
        code: pack01
        stock: 25
        category: nacional
        status: true
        owner: admin
  requestBodies:
    createUser:
      type: object
      properties:
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripción del producto
        price:
          type: Number
          description: Precio del producto
        thumbnails:
          type: Array
          description: Fotos del producto
        code:
          type: String
          description: Código del producto
        stock:
          type: Number
          description: Cantidad de productos en stock
        category:
          type: String
          description: Categoría del producto
        status:
          type: Boolean
          description: Disponibilidad del producto
        owner:
          type: String
          description: Creador del producto
      example:
        _id: 654e8d9cdd7bc5ac119b66c0
        title: Valle de Punilla + Traslasierra
        description: 7 días, 6 noches
        price: 100
        thumbnails: [Sin imagen]
        code: pack01
        stock: 25
        category: nacional
        status: true
        owner: admin
    updateUser:
      type: object
      properties:
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripción del producto
        price:
          type: Number
          description: Precio del producto
        thumbnails:
          type: Array
          description: Fotos del producto
        code:
          type: String
          description: Código del producto
        stock:
          type: Number
          description: Cantidad de productos en stock
        category:
          type: String
          description: Categoría del producto
        status:
          type: Boolean
          description: Disponibilidad del producto
      example:
        _id: 654e8d9cdd7bc5ac119b66c0
        title: Valle de Punilla + Traslasierra
        description: 7 días, 6 noches
        price: 100
        thumbnails: [Sin imagen]
        code: pack01
        stock: 25
        category: nacional
        status: true
        owner: admin